-- ============================================================
-- Migration 009: Product-Aware Generation Engine
-- ============================================================
-- Enables:
--   1. pgvector columns on catalog_products for CLIP + IP-Adapter embeddings
--   2. generation_log table — tracks every AI generation for cost monitoring
--   3. user_generation_quota table — enforces free tier (3/month) limit
--   4. match_products_by_image() RPC — pgvector similarity search
--   5. get_user_quota() RPC — quota check before generation starts
-- ============================================================

-- pgvector is already enabled (user confirmed in dashboard)

-- ============================================================
-- 1. CATALOG PRODUCTS TABLE
-- Stores all 399 products from productCatalog.js with embeddings.
-- The app's local JS catalog is the source of truth for product
-- data; this table mirrors it + adds the vector columns that
-- can't live in a JS file.
-- ============================================================

CREATE TABLE IF NOT EXISTS catalog_products (
  id                    TEXT PRIMARY KEY,          -- matches productCatalog.js id (e.g. "amz-001")
  asin                  TEXT,
  name                  TEXT NOT NULL,
  brand                 TEXT,
  price                 NUMERIC(10,2),
  price_display         TEXT,
  image_url             TEXT,
  affiliate_url         TEXT,
  category              TEXT,
  room_type             TEXT[],
  styles                TEXT[],
  materials             TEXT[],
  tags                  TEXT[],
  description           TEXT,
  rating                NUMERIC(3,1),
  review_count          INTEGER,
  source                TEXT DEFAULT 'amazon',

  -- ── Visual description (used in generation prompt + vision matching) ──────
  -- One sentence describing the product as an artist would see it.
  -- e.g. "curved cream boucle sofa with low profile and tapered walnut legs"
  visual_description    TEXT,

  -- ── CLIP ViT-L/14 embedding (512d) — for similarity search ──────────────
  -- Generated by the Python ML microservice /embed/clip endpoint.
  -- Used by match_products_by_image() to find visually similar products.
  -- Cost: one-time batch encode (~$0.00, runs on Railway server)
  clip_embedding        vector(512),

  -- ── IP-Adapter ViT-H/14 embedding (1024d) — for generation guidance ──────
  -- Generated by the Python ML microservice /embed/ip-adapter endpoint.
  -- Fed directly into fofr/sdxl-multi-controlnet-lora at inpainting time.
  -- Skips re-encoding the product image at generation time (saves ~0.5s/pass).
  ip_adapter_embedding  vector(1024),

  -- ── Dominant colors (jsonb array) ────────────────────────────────────────
  -- Extracted by the ML microservice during batch encoding.
  -- e.g. [{"hex": "#C8B89A", "name": "warm beige", "pct": 0.42}, ...]
  -- Used by visionMatcher.js color scoring — more reliable than tag parsing.
  dominant_colors       JSONB DEFAULT '[]',

  -- ── Visual attributes (jsonb) ─────────────────────────────────────────────
  -- Structured attributes from enrichCatalog.js — shape, texture, legStyle, etc.
  -- e.g. {"shape": "curved", "texture": "boucle", "legStyle": "tapered", ...}
  visual_attributes     JSONB DEFAULT '{}',

  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast category + room type filtering during similarity search
CREATE INDEX IF NOT EXISTS idx_catalog_products_category
  ON catalog_products (category);

CREATE INDEX IF NOT EXISTS idx_catalog_products_source
  ON catalog_products (source);

-- pgvector HNSW index for fast approximate nearest-neighbor search
-- (faster than IVFFlat for catalogs under 100k products)
-- ef_construction=128, m=16 — good balance of speed vs recall
CREATE INDEX IF NOT EXISTS idx_catalog_products_clip_embedding
  ON catalog_products USING hnsw (clip_embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 128);

CREATE INDEX IF NOT EXISTS idx_catalog_products_ip_adapter_embedding
  ON catalog_products USING hnsw (ip_adapter_embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 128);

-- ============================================================
-- 2. GENERATION LOG TABLE
-- Every AI generation is logged here for:
--   - Cost tracking and monitoring
--   - Quota enforcement (free tier: 3/month)
--   - Debugging failed generations
--   - Analytics (which styles are most popular, etc.)
-- ============================================================

CREATE TABLE IF NOT EXISTS generation_log (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID REFERENCES profiles(id) ON DELETE SET NULL,

  -- Generation inputs
  prompt                TEXT,
  room_type             TEXT,
  style                 TEXT,

  -- Generation outputs
  result_image_url      TEXT,
  matched_product_ids   TEXT[],           -- IDs of products shown to user
  vision_analysis       JSONB,            -- Claude Vision output (for debugging)

  -- Pipeline tracking
  tier                  TEXT DEFAULT 'free',   -- 'free' | 'premium'
  pipeline_version      TEXT DEFAULT 'v2',     -- 'v1' (text only) | 'v2' (vision) | 'v3' (product-aware)
  passes_completed      INTEGER DEFAULT 0,     -- number of inpainting passes completed
  generation_status     TEXT DEFAULT 'pending', -- 'pending' | 'completed' | 'failed'

  -- ── Cost tracking (in USD) ────────────────────────────────────────────────
  -- Every API call cost is logged individually so we can audit line by line.
  cost_pass1_usd        NUMERIC(8,6) DEFAULT 0,  -- flux-depth-dev room generation
  cost_inpaint_usd      NUMERIC(8,6) DEFAULT 0,  -- fofr sdxl inpainting (all passes combined)
  cost_vision_usd       NUMERIC(8,6) DEFAULT 0,  -- Claude Haiku vision analysis
  cost_segment_usd      NUMERIC(8,6) DEFAULT 0,  -- MobileSAM (Railway amortized cost)
  cost_total_usd        NUMERIC(8,6)              -- computed: sum of all costs above

    GENERATED ALWAYS AS (
      cost_pass1_usd + cost_inpaint_usd + cost_vision_usd + cost_segment_usd
    ) STORED,

  -- Timing
  duration_ms           INTEGER,                 -- total generation time in milliseconds
  created_at            TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for cost reporting queries
CREATE INDEX IF NOT EXISTS idx_generation_log_user_id
  ON generation_log (user_id);

CREATE INDEX IF NOT EXISTS idx_generation_log_created_at
  ON generation_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_generation_log_tier
  ON generation_log (tier);

-- ============================================================
-- 3. USER GENERATION QUOTA TABLE
-- Tracks monthly free tier usage per user.
-- Free tier: 3 generations/month (resets on 1st of each month).
-- Premium tier: unlimited (quota_limit = -1).
-- ============================================================

CREATE TABLE IF NOT EXISTS user_generation_quota (
  user_id               UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  tier                  TEXT DEFAULT 'free',      -- 'free' | 'premium'
  quota_limit           INTEGER DEFAULT 3,        -- -1 = unlimited (premium)
  generations_used      INTEGER DEFAULT 0,        -- resets monthly
  quota_reset_date      DATE DEFAULT DATE_TRUNC('month', NOW())::DATE + INTERVAL '1 month',
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 4. RPC: match_products_by_image
-- Finds the most visually similar catalog products to a given
-- CLIP embedding vector. Called by generate-with-products edge
-- function after segmenting furniture regions.
--
-- Cost: ~$0.00 per call (pure Postgres vector math, no API)
-- Speed: <10ms with HNSW index on 399 products
-- ============================================================

CREATE OR REPLACE FUNCTION match_products_by_image(
  query_embedding   vector(512),
  match_threshold   FLOAT DEFAULT 0.6,
  match_count       INTEGER DEFAULT 6,
  category_filter   TEXT DEFAULT NULL
)
RETURNS TABLE (
  id                TEXT,
  name              TEXT,
  brand             TEXT,
  price             NUMERIC(10,2),
  price_display     TEXT,
  image_url         TEXT,
  affiliate_url     TEXT,
  category          TEXT,
  visual_description TEXT,
  dominant_colors   JSONB,
  similarity        FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.name,
    p.brand,
    p.price,
    p.price_display,
    p.image_url,
    p.affiliate_url,
    p.category,
    p.visual_description,
    p.dominant_colors,
    1 - (p.clip_embedding <=> query_embedding) AS similarity
  FROM catalog_products p
  WHERE
    p.clip_embedding IS NOT NULL
    AND 1 - (p.clip_embedding <=> query_embedding) > match_threshold
    AND (category_filter IS NULL OR p.category = category_filter)
  ORDER BY p.clip_embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ============================================================
-- 5. RPC: get_user_quota
-- Called at the START of every generation to check if the user
-- is allowed to generate. Returns quota info so the app can
-- show "2 of 3 free generations used" in the UI.
--
-- Also handles monthly reset: if quota_reset_date has passed,
-- resets generations_used to 0 automatically.
-- ============================================================

CREATE OR REPLACE FUNCTION get_user_quota(p_user_id UUID)
RETURNS TABLE (
  tier              TEXT,
  quota_limit       INTEGER,
  generations_used  INTEGER,
  generations_remaining INTEGER,
  can_generate      BOOLEAN,
  quota_reset_date  DATE
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_record user_generation_quota%ROWTYPE;
  v_today  DATE := CURRENT_DATE;
BEGIN
  -- Get or create quota record
  SELECT * INTO v_record
  FROM user_generation_quota
  WHERE user_id = p_user_id;

  IF NOT FOUND THEN
    INSERT INTO user_generation_quota (user_id)
    VALUES (p_user_id)
    RETURNING * INTO v_record;
  END IF;

  -- Monthly reset: if reset date has passed, zero out the counter
  IF v_today >= v_record.quota_reset_date THEN
    UPDATE user_generation_quota
    SET
      generations_used = 0,
      quota_reset_date = DATE_TRUNC('month', v_today)::DATE + INTERVAL '1 month',
      updated_at       = NOW()
    WHERE user_id = p_user_id
    RETURNING * INTO v_record;
  END IF;

  RETURN QUERY SELECT
    v_record.tier,
    v_record.quota_limit,
    v_record.generations_used,
    CASE
      WHEN v_record.quota_limit = -1 THEN 999   -- unlimited
      ELSE GREATEST(0, v_record.quota_limit - v_record.generations_used)
    END AS generations_remaining,
    CASE
      WHEN v_record.quota_limit = -1 THEN TRUE  -- premium: always can generate
      ELSE v_record.generations_used < v_record.quota_limit
    END AS can_generate,
    v_record.quota_reset_date;
END;
$$;

-- ============================================================
-- 6. RPC: increment_generation_count
-- Called AFTER a successful generation to increment the counter.
-- Called from generate-with-products edge function only.
-- ============================================================

CREATE OR REPLACE FUNCTION increment_generation_count(p_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO user_generation_quota (user_id, generations_used)
  VALUES (p_user_id, 1)
  ON CONFLICT (user_id) DO UPDATE
  SET
    generations_used = user_generation_quota.generations_used + 1,
    updated_at       = NOW();
END;
$$;

-- ============================================================
-- 7. RPC: get_cost_summary
-- Admin-facing cost monitoring. Returns total spend by tier,
-- pipeline version, and time period.
-- Cost is tracked per generation in generation_log.
-- ============================================================

CREATE OR REPLACE FUNCTION get_cost_summary(
  p_start_date TIMESTAMPTZ DEFAULT NOW() - INTERVAL '30 days',
  p_end_date   TIMESTAMPTZ DEFAULT NOW()
)
RETURNS TABLE (
  tier                  TEXT,
  pipeline_version      TEXT,
  total_generations     BIGINT,
  total_cost_usd        NUMERIC(10,4),
  avg_cost_per_gen_usd  NUMERIC(8,6),
  avg_duration_ms       NUMERIC(10,0)
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    g.tier,
    g.pipeline_version,
    COUNT(*)::BIGINT                          AS total_generations,
    SUM(g.cost_total_usd)::NUMERIC(10,4)      AS total_cost_usd,
    AVG(g.cost_total_usd)::NUMERIC(8,6)       AS avg_cost_per_gen_usd,
    AVG(g.duration_ms)::NUMERIC(10,0)         AS avg_duration_ms
  FROM generation_log g
  WHERE
    g.created_at BETWEEN p_start_date AND p_end_date
    AND g.generation_status = 'completed'
  GROUP BY g.tier, g.pipeline_version
  ORDER BY g.tier, g.pipeline_version;
END;
$$;

-- ============================================================
-- 8. ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE catalog_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE generation_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_generation_quota ENABLE ROW LEVEL SECURITY;

-- catalog_products: public read (anyone can see products), no write from client
CREATE POLICY "catalog_products_public_read"
  ON catalog_products FOR SELECT
  USING (TRUE);

-- generation_log: users see only their own logs
CREATE POLICY "generation_log_own_rows"
  ON generation_log FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "generation_log_insert_own"
  ON generation_log FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- user_generation_quota: users see only their own quota
CREATE POLICY "quota_own_row"
  ON user_generation_quota FOR SELECT
  USING (auth.uid() = user_id);
